sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
  - bash dockerfiles/build.sh
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - docker --version

install:
  - pip install planemo

script:
  - bash test.sh

deploy:
  provider: script
  script: bash ./dockerfiles/deploy.sh
  on:
    branch: master
